### PR TITLE
Adding hashtags

### PR DESCRIPTION
**Pull request by applemuncy**
Simple
a#Active_Devices 
translates into
<a id="Active_Devices"> </a)

Maybe works. I can't test it. 
: )

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
I've banged my head on npm for long enough tonight. You win.

**Comment by NeoTheThird** [comment]
Ok, now i feel stupid. Thanks @applemuncy

**Comment by applemuncy** [comment]
Is it actually working?  It's not working for me : (

**Comment by NeoTheThird** [comment]
No, it doesn't. I wrote that comment before testing. Is there a way to test the website locally? I could not make sense of it

**Comment by applemuncy** [comment]
I'm thinking this thing is build by an application and not meant to be hacked by hand. 

I assume there must be an application that can test it but I don't know what it is.

**Comment by applemuncy** [comment]
When I look at the page source as displayed by a browser, I see that there is a container that would need to be split into three partsv, each could then have a #tag.

**Comment by UniversalSuperBox** [comment]
Getting this running on your computer *should* be as easy as cloning the repository then running `npm install && npm start` inside. This is not the case for Ubuntu 16.10, but might work on earlier versions. I haven't tested again since I merged.

**Comment by UniversalSuperBox** [comment]
Also, please continue discussion on https://github.com/ubports/devices.ubports.com/issues/9

**Comment by applemuncy** [comment]
I'm thinking this thing is build by an application and not meant to be hacked by hand. 

I assume there must be an application that can test it but I don't know what it is.

**Pull request merged**
